# Generated by Django 4.1.7 on 2023-09-11 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "ordering": ("-create_datetime",),
                "verbose_name": "Логгер",
                "verbose_name_plural": "Логгер",
            },
        ),
    ]
