# Generated by Django 5.0.2 on 2024-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
