# Generated by Django 5.0.6 on 2025-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_spares_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
