# Generated by Django 5.0.6 on 2025-08-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_spares_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='units')),
            ],
            options={
                'verbose_name': 'Агрегат',
                'verbose_name_plural': 'Агрегаты',
            },
        ),
        migrations.AddField(
            model_name='spares',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.units'),
        ),
    ]
