# Generated by Django 5.0.6 on 2025-08-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_units_spares_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'Группа комплектующего', 'verbose_name_plural': 'Группы комплектующих'},
        ),
        migrations.AddField(
            model_name='spares',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярность сейчас'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.units', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='truck',
            field=models.ManyToManyField(to='truck.truck', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='units',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
