# Generated by Django 5.0.6 on 2026-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_alter_units_options_spares_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spares'),
        ),
    ]
