# Generated by Django 5.0.6 on 2026-06-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0006_alter_spares_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spares',
            name='photo',
        ),
        migrations.AlterField(
            model_name='spares',
            name='truck',
            field=models.ManyToManyField(blank=True, null=True, to='truck.truck', verbose_name='Техника'),
        ),
        migrations.CreateModel(
            name='ImagesSpares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spares', verbose_name='Изображение')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='truck.spares', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Изображение запчасти',
                'verbose_name_plural': 'Изображения запчастей',
            },
        ),
    ]
