# Generated by Django 5.0.6 on 2026-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0007_remove_spares_photo_alter_spares_truck_imagesspares'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
