# Generated by Django 5.0.6 on 2026-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_spares_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesspares',
            options={'ordering': ['order'], 'verbose_name': 'Изображение запчасти', 'verbose_name_plural': 'Изображения запчастей'},
        ),
        migrations.AddField(
            model_name='imagesspares',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
