name: truck CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t truck_back .
        # Если это облачный раннер, здесь обычно добавляют шаг авторизации
        # и отправки (push) образа в Docker Registry, чтобы deploy-job мог его скачать.

  test-job:
    runs-on: ubuntu-latest
    needs: build-job # Запустится только после успешного билда
    steps:
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          echo "Finishing unit tests..."

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job # Запустится только после успешных тестов
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Нужен, чтобы получить файл docker-compose.yml

      - name: Deploy with Docker Compose
        run: docker compose up -d